name: Use Secret Example

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the GitHub Secret securely
        run: |
          echo "Using the secret without exposing it"
          echo "The secret is ${{ secrets.SECRET }}" | sha256sum > /dev/null
